INSTALL:expand dependency information
I added this because I received this error when compiling vslib:

```
In file included from conmenu.cpp:12:0:
./unicon.h:22:26: fatal error: yascreen.h: No such file or directory
     #include <yascreen.h>
                          ^
compilation terminated.
makefile:242: recipe for target '.OBJ.libvscony.a/conmenu.o' failed
make: *** [.OBJ.libvscony.a/conmenu.o] Error 1
```